name: kagi_api
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.2.3

dependencies:
  http: ^1.1.2
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  rexios_lints: ^6.0.1
  test: ^1.24.0
